#!/bin/bash
# Author: Gacha
# Description: To zip and unzip Lolita's or Lolita's plugins Git files
# Usage: just run it

if [ "$(basename `pwd`)" == "$(basename `pwd` | grep -oE lolita[a-z0-9_]*)" ]; then
  if [ -f ".git.zip" ]; then
    if [ "$(unzip -q .git.zip)" == "" ]; then
      rm .git.zip
      echo "Unzipping [ok]"
    else
      echo "Unzipping [failed]"
    fi
  else
    if [ -d ".git" ]; then
      if [ -z "$(git diff)" ]; then
        zip -qr .git.zip .git .gitignore
        if [ -f ".git.zip" ]; then
          rm -rf .git .gitignore
          echo "Zipping [ok]"
        else
          echo "Zipping [failed]"
        fi
      else
        echo "Please commit changes first"
      fi
    else
      echo "No .git directory found"
    fi
  fi
else
  echo "We are not in Lolita's or Lolita's plugin dir!"
fi
