#!/bin/bash
# Author: Gacha
# Description: To zip and unzip Lolita's or Lolita's plugins Git files
# Usage: just run it

if [ "$(basename `pwd`)" == "$(basename `pwd` | grep -oE lolita[a-z0-9_]*)" ]; then
  if [ -f ".git.zip" ]; then
    unzip .git.zip
    if [ -d ".git" ] && [ -f ".gitignore" ]; then
      rm .git.zip
    fi
  else
    if [ -d ".git" ] && [ -f ".gitignore" ]; then
      if [ -z "$(git diff)" ]; then
        zip -r .git.zip .git .gitignore
        if [ -f ".git.zip" ]; then
          rm -rf .git .gitignore
        fi
      else
        echo "Commit changes first"
      fi
    else
      echo "No .git OR .gitignore found"
    fi
  fi
else
  echo "We are not in Lolita's or Lolita's plugin dir!"
fi
